### PR TITLE
📔 Api documentation

### PR DESCRIPTION
**Pull request by mrsegen**

### CODE REVIEW

**Comment by thibaultyou** [comment]
Thank you for this, should make things clearer for most users.

I've updated the Postman collection with a few things, I need to update the Swagger to match modifications.
Maybe we need to find a proper way to deploy the Swagger to Github pages or some kind of alternative.

Once this is done we can remove the previous Markdown api documentation.

Any thought or personal preference ?

**Comment by mrsegen** [comment]
If Postman is good-to-go, we could remove the swagger stuff for now and move forward with it?

If it's worth pursuing Swagger, I'd probably next try to implement something using [their guide](https://github.com/peter-evans/swagger-github-pages#steps-to-manually-configure-in-your-own-repository).

I'm still torn between the two. Postman has lots of utility (e.g. scriptable, can save local edits that persist between sessions of the app). Swagger has low threshold for entry because it can be served and used to call a in a browser, and I'm just more familiar with it and have biased affinity because I contributed to it a bit ago. At the moment, I'd either defer to your preference if you have one, or be fine with both for the time being.

**Comment by thibaultyou** [comment]
@mrsegen are we ok to merge this one ?

**Comment by mrsegen** [comment]
Oh, I missed your question. Yep!

**Pull request merged**
